### ISSUE TITLE
Can't install the package from NuGet

### ISSUE THREAD

**Issue by eugene-chehovskoy** [neisbut/Npgsql.Bulk#1]
Hi,

I receive this error in console during installation:
```
GET https://api.nuget.org/v3-flatcontainer/npgsql.entityframeworkcore.postgres/index.json
NotFound https://api.nuget.org/v3-flatcontainer/npgsql.entityframeworkcore.postgres/index.json 669ms
Install-Package : Unable to find package Npgsql.EntityFrameworkCore.Postgres. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
```

It looks like a typo in dependency package name "Npgsql.EntityFrameworkCore.Postgres" should be "Npgsql.EntityFrameworkCore.PostgreSQL".

**Comment by neisbut** [comment]
Hi @eugene-chehovskoy, thanks for raising this. Dumb mistake. I've fixed this in 0.5.7 and update NuGet package. Please check.

**Comment by eugene-chehovskoy** [comment]
After updating, installation completed successfully. You can close the issue, Thanks!

**Comment by neisbut** [comment]
Great!
