### ISSUE TITLE
Allow to use Insert IEnumerable without ToList

### ISSUE THREAD

**Issue by nazar554** [neisbut/Npgsql.Bulk#10]
Currently the `Insert` method calls `entities.ToList()`, is it possible to provide one without it (for large data sets)? It's okay if it doesn't use a temp table and has no the `returning` clause, just for fast inserts.

**Comment by neisbut** [comment]
Hi @nazar554, thanks for the interest in this project! Actually this sounds interesting, I think I will implement this suggestion (will take some time thought). Will be back to you when done.

**Comment by neisbut** [comment]
Hi @nazar554, I've just uploaded Npgsql.Bulk v 0.6.4 to NuGet. There is a new `Import` operation. Please try it. I hope it is what you needed.

**Comment by nazar554** [comment]
Thanks, seems to work
