### ISSUE TITLE
Wrong NET Core IsDbGenerated value when Property has HasValueGenerator annotation

### ISSUE THREAD

**Issue by pacoferre** [neisbut/Npgsql.Bulk#11]
On this line:

https://github.com/neisbut/Npgsql.Bulk/blob/53a9ffda1cfc0e1ad134259b65190d764c29c3f5/src/Npgsql.Bulk.DotNetStandard15/NpgsqlHelper.cs#L98

Perhaps it should be:

`IsDbGenerated = x.ValueGenerated != ValueGenerated.Never
                            && !x.GetAnnotations().Any(a => a.Name == "ValueGeneratorFactory")`

When a Property includes this DBContext configuration.

`.HasValueGenerator<MyOwnValueGenerator>()
.ValueGeneratedOnAdd()`

It is excluded from Insert statements because IsDbGenerated = true (the OnAdd ValueGenerated value). So the insert fails because of NULL value sent to database.

**Comment by neisbut** [comment]
Hi @pacoferre, wow, you right, I missed this. Let me check this and be back to you with a fix.

**Comment by neisbut** [comment]
Hi @pacoferre, I implemented value generators in 0.6.5 release, please check if it works right for you.

**Comment by pacoferre** [comment]
Thanks @neisbut, I'll tell you.

**Comment by pacoferre** [comment]
Hi @neisbut,

I had to make little changes in my code, but finally worked.

The problem occurs when I add an object to the context. So EntityFramework calls the value generator for the keys, but when I call uploader.Insert, there is a function called "SetAutoGeneratedFields" who call the generators again... so the FKs fails in some cases.

For example, in complex objects (parent -> child), when previously I added them to Context, all the keys and FKs where correct. Now, I don't add them to context and have to make little things like this.

`            uploader.Insert(toAdd);

            toAdd  // This is new
                .ForEach(item => item.ChildreenCollection?
                    .ToList()
                    .ForEach(child => {
                        child.ParentId = item.ParentId;
                    }));

            uploader.Insert(toAdd.SelectMany(_ => _.ChildreenCollection));`

This is not an issue for me, but perhaps someone else would prefer that uploader.Insert doesn't call SetAutoGeneratedFields method.

**Comment by neisbut** [comment]
Hi @pacoferre, ah, I think I got the issue.. I've commited one more change to github (but not to NuGet for now). With this change auto generation should not be run for attached entities. Could you please try on your side if that change helps you? Now: when entity is attached - SetAutoGeneratedFields won't be called. If entity is not attched - it will be called.

**Comment by pacoferre** [comment]
Hi @neisbut, it works great :)

Tried with attached and un-attached entities, all perfect.

Thanks a lot.

**Comment by neisbut** [comment]
Hi @pacoferre, awesome! Released 0.6.6 to NuGet!

**Comment by pacoferre** [comment]
Great, this issue can be closed... I think :)
