### ISSUE TITLE
Add support for List<string> properties 

### ISSUE THREAD

**Issue by pacoferre** [neisbut/Npgsql.Bulk#12]
If an entity has a property based on List<string>, the type name is "_text" and it throws an Exception.

https://github.com/neisbut/Npgsql.Bulk/blob/5f9076f092f57971abd9790cf9e7cd08662701c2/src/Npgsql.Bulk/NpgsqlBulkUploader.cs#L94-L99

So, I added this:

`                case "_text":
                    return NpgsqlDbType.Array;
`

And it works... don't know what happens with List<int> properties, perhaps in some days :)

**Comment by neisbut** [comment]
Hi @pacoferre, thanks for suggestion! I will implement this soon :)

**Comment by pacoferre** [comment]
Hi @neisbut, I have one more case to add :)

`                case "bytea":
                    return NpgsqlDbType.Bytea;
`

This is useful for byte[] properties.

**Comment by neisbut** [comment]
Hi @pacoferre, implemented both in 0.6.5 release, please check :)

**Comment by pacoferre** [comment]
Great, I'll tell you, thanks a lot :)

**Comment by pacoferre** [comment]
Hi @neisbut,

All working for _text and bytea... this issue can be closed.

Thanks a lot
