### ISSUE TITLE
Support for NpgsqlRange<Instant> properties

### ISSUE THREAD

**Issue by pacoferre** [neisbut/Npgsql.Bulk#13]
Hello again :)

I'm trying to use a new property for tsrange type.

        [Required]
        public NpgsqlRange<Instant> Duration { get; set; }

First I added

                case "tsrange":
                    return NpgsqlDbType.Range;

after

https://github.com/neisbut/Npgsql.Bulk/blob/243ded5ff8483315204f9e88ef3b0f99e31d5c78/src/Npgsql.Bulk/NpgsqlBulkUploader.cs#L97-L98

But there is an error I cannot debug on.

https://github.com/neisbut/Npgsql.Bulk/blob/243ded5ff8483315204f9e88ef3b0f99e31d5c78/src/Npgsql.Bulk/NpgsqlBulkUploader.cs#L208

It just jump to catch section and the Exception says:

System.InvalidProgramException
  HResult=0x8013153A
  Message=Common Language Runtime detected an invalid program.
  Source=Dwell_636891960223685689
  StackTrace:
   at Dwell_636891960223685689.ClientDataWriter(Dwell , NpgsqlBinaryImporter )
   at Npgsql.Bulk.NpgsqlBulkUploader.Insert[T](IEnumerable`1 entities, InsertConflictAction onConflict) in C:\work\tos\external\Npgsql.Bulk\src\Npgsql.Bulk\NpgsqlBulkUploader.cs:line 214
   at Npgsql.Bulk.NpgsqlBulkUploader.Insert[T](IEnumerable`1 entities) in C:\work\tos\external\Npgsql.Bulk\src\Npgsql.Bulk\NpgsqlBulkUploader.cs:line 146

**Comment by neisbut** [comment]
Hi again @pacoferre :) Wow, let me investiage this issue soon and be back to you. Surprised it doesn't work for this type.

**Comment by pacoferre** [comment]
Thanks a lot @neisbut :)

Tell me if I can help in any way... I didn't have time to investigate further :(

**Comment by neisbut** [comment]
Hi @pacoferre, no problem, you did a lot already :) I tried on my side and found the reason. Fixed it in 0.6.7 release (worked for me perfectly). But have one doubt: I didn't use NodaTime and used NpgsqlRange<DateTime> instead. So need your confirmation if this issue is fixed now, so please check whenever you have time. Thanks!

**Comment by pacoferre** [comment]
Hi @neisbut, it works great :)

The data type for NpgsqlRange<Instant> is tsrange in postgresql, so I can store also "opened" durations 🥇 

![image](https://user-images.githubusercontent.com/10376690/55400134-56495500-554d-11e9-9ab7-5778cfd28f7e.png)
Hehe, now I can remove StartTime and EndTime fields :)

Thanks a lot for the awesome work

**Comment by pacoferre** [comment]
Hello again @neisbut,

There is an issue about Nullable NpgsqlRange<T> properties, for example:


    public NpgsqlRange<Instant>? Duration { get; set; }


I think there is something needed in

https://github.com/neisbut/Npgsql.Bulk/blob/b57e0a52cf9ab73234efe770bfafd2cd05c420eb/src/Npgsql.Bulk/NpgsqlBulkCodeBuilder.cs#L192-L195

But I haven't found it :(

**Comment by neisbut** [comment]
Hi @pacoferre, sorry for this. I didn't check Nullable part. :( Fixed now, pleae try it out in 0.6.8 release.

**Comment by pacoferre** [comment]
Hi @neisbut,

Works perfect, thanks a lot again :)
