### ISSUE TITLE
Async versions of methods

### ISSUE THREAD

**Issue by amburin** [neisbut/Npgsql.Bulk#18]
Are you planning to implement async versions of Import, Update and Insert?

**Comment by neisbut** [comment]
Hi @amburin, well, I didn't think about that before you asked :D But now I think it is a good idea. So, yes, I will do it in next weeks. Thanks for the tip!

**Comment by neisbut** [comment]
Hi @amburin , actually it seems there is no async version of `BeginBinaryImport` as per (https://github.com/npgsql/npgsql/issues/1632). So some code won't be that async.

**Comment by neisbut** [comment]
Hi @amburin, I've implemented async methods. So you can try them in v0.7.0. Thanks!

**Comment by amburin** [comment]
Awesome! I will try this.
