### ISSUE TITLE
.NET Framework 4.5 hampers contribution

### ISSUE THREAD

**Issue by amburin** [neisbut/Npgsql.Bulk#22]
New contributors have to install **.NET Framework 4.5 Developer Pack**  to build this project. But **.NET Framework 4.5 Developer Pack** is no longer available from [MS downloads page](https://dotnet.microsoft.com/download/visual-studio-sdks), so they would spend time to find it. somewhere else.

I suggest to Increase target framework version to 4.5.2, so user can easily download **Developer Pack** and begin to contribute.

**Comment by neisbut** [comment]
Hi @amburin, thanks for pointing this! Seems my machine is that old, so I didn't spot this. Done, I've changed Framework version to 4.5.2.
