### ISSUE TITLE
Nuget package targeting .NET Framework can't utilize EFCore

### ISSUE THREAD

**Issue by weweilep** [neisbut/Npgsql.Bulk#26]
The nuget package, as it exists now, only supplies EF6 support when targeting a .NET Framework executable.  EFCore is supported on .NET Framework through .NET Standard.  While your package has a .NET Standard library, it cannot be applied to .NET Framework because the .NET Framework library takes precedent, and there is no way to override that action.

Would it be possible to break this into two nuget packages, one for EF6 and one for EFCore?  Something along the lines of Npgsql.Bulk.EF6 and Npgsql.Bulk.EFCore?  Both could have a .NET Framework and a .NET Standard library (EF6 is coming to .NET Core in 3.0).

**Comment by neisbut** [comment]
Hi @weweilep, I'm happy to help, but help me to understand this case better. You have .Net Framework project and you want to use Npgsql.Bulk, but EF Core (via .Net Standard)? Is it because you need some features of EF Core or why?

**Comment by weweilep** [comment]
Say you have a data library written in .NET Standard.  You attach a nuget package (like Npgsql.Bulk) to that library.  Then you have a .NET Framework (4.6.1+) application which consumes the .NET Standard data library, Nuget will package the .NET Framework version of associated libraries.  If your .NET Standard data library uses EF6, your package works fine, but if it targets EFCore, it doesn't work at all.

EF6 & EFCore are not directly compatible/swappable.

It is possible to have:
-.NET Framework + EF6 via .NET Framework
-.NET Framework + EFCore via .NET Standard (.NET Framework 4.6.1+)
-.NET Core + EFCore
-.NET Core + EF6 (upcoming via .NET Standard + .NET Core 3)

Having a single package swap them based on framework is incorrect and can cause unexpected results.

**Comment by neisbut** [comment]
Hi @weweilep. Now I understand that better. Still confused by the following: 

> Both could have a .NET Framework and a .NET Standard library (EF6 is coming to .NET Core in 3.0).

Shouldn't Npgsql.Bulk.EF6 has target framework = .Net Framework and Npgsql.Bulk.EFCore has =  .NET Standard ?

**Comment by weweilep** [comment]
> Shouldn't Npgsql.Bulk.EF6 has target framework = .Net Framework and Npgsql.Bulk.EFCore has = .NET Standard ?

Npgsql.Bulk.EFCore would only need .NET Standard 2.0 target, but Npgsql.Bulk.EF6 could actually need both .NET Framework and .NET Standard depending on what it is paired with.

For EF6, anyone using .NET Framework prior to 4.6.1 would need either a matching .NET Framework or a .NET Standard lower than 2.0 and I believe EF6 coming to .NET Core 3.0 will require .NET Standard 2.0.

**Comment by neisbut** [comment]
Hi @weweilep, ok, this makes sense. I think I will create a separate package ...EFCore with .NET Standard 2.0 target only. Hope that will solve this issue. Problem right now is that I can't use name Npgsql.Bulk.EfCore (prefix is reserved now). Maybe I will have to use name like NpgsqlBulk.EfCore. Trying to resolve this at the moment..

**Comment by neisbut** [comment]
Hi @weweilep, published EF Core version with another name https://www.nuget.org/packages/NpgsqlBulk.EFCore Please try if possible.

**Comment by weweilep** [comment]
Works great, thank you!  I've only tried bulk insert so far using EFCore on .NET Standard consumed by a .NET Framework application.  Dropped my 37 second job down to about 2.5 seconds.

**Comment by weweilep** [comment]
I haven't had time to test extensively yet, but .NET Standard with EF Core appears to have issues with UpdateAsync when executing on CentOS/Linux against PostgreSQL 11.  No exception, but no save either.  InsertAsync appears to work as expected.  UpdateAsync works on Windows.  I did not try non-async Update on either platform yet.

**Comment by neisbut** [comment]
Hi @weweilep, oh, that's weird. Is it possible to check if non-async Update works?

**Comment by weweilep** [comment]
What's even weirder is I just tried to write a simple test-case, and it works fine on CentOS using asynchronous or synchronous there.  I'm closing this for now, and if I can find a specific reproduction case, I'll create a separate issue for that.

Thank you for making the separated package, it is appreciated!
