### ISSUE TITLE
Would it be possible to support Enum columns?

### ISSUE THREAD

**Issue by advnodequest** [neisbut/Npgsql.Bulk#29]
The GetNpgsqlType method in NpgsqlBulkUploader returns a  NpgsqlDbType.
The list of Npgsql DB types doesn't include an enum type, although PostgreSQL does support enums.
https://www.npgsql.org/doc/api/NpgsqlTypes.NpgsqlDbType.html

So it seems obvious why Npgsql.Bulk doesn't support Enum columns at the moment.
But I'm wondering if there is a way Enum columns might be supported nonetheless?

**Comment by neisbut** [comment]
Hi @advnodequest , sorry, don't get the point? What setup do you have? Any exception you face?

If you mean clr enums then they are supported, in test project Enum is used like this:

        [Column("type")]
        public AddressType? Type { get; set; }

**Comment by neisbut** [comment]
Closed due to inactivity.
