### ISSUE TITLE
EF Core 3.0 : TypeLoadException for RelationalMetadataExtensions

### ISSUE THREAD

**Issue by Krashlog** [neisbut/Npgsql.Bulk#34]
Hi,

I don't know if EF Core 3.0 is supported by this library, but I'm trying to upgrade a project to that version and I'm getting this exception when using the BulkUploader :

**System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.RelationalMetadataExtensions' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.**

Here is the full stack trace :

```
System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.RelationalMetadataExtensions' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Npgsql.Bulk.NpgsqlHelper.GetTableName(DbContext context, Type t)
   at Npgsql.Bulk.NpgsqlBulkUploader.CreateEntityInfo[T]()
   at Npgsql.Bulk.NpgsqlBulkUploader.<GetEntityInfo>b__40_0[T](Type x)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Npgsql.Bulk.NpgsqlBulkUploader.GetEntityInfo[T]()
   at Npgsql.Bulk.NpgsqlBulkUploader.InsertAsync[T](IEnumerable`1 entities, InsertConflictAction onConflict)
```

Other (non-bulk) database operations work without problems. 

Anything obvious I should check on my side? Thanks.

**Comment by neisbut** [comment]
Hi @Krashlog, what version of Npgsql.Bulk you are using? 0.7.6 works fine in .Net Core 3 app for me.

**Comment by Krashlog** [comment]
Yes, I'm on 0.7.6. The same application runs flawlessly on 0.7.5 (on .Net Core 2.2).

The app is quite large, I'll try to provide a small repro and investigate further.

**Comment by Krashlog** [comment]
After digging some more I think it's because of changes in the latest release of Npgsql.EntityFrameworkCore.PostgreSQL. They broke compatibility and had to revert changes in a hotfix, so the version I'm using (3.0.1) has a dependency on Ngpsql 4.1.1 : 

https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/releases/tag/v3.0.1
https://github.com/npgsql/npgsql/releases/tag/v4.1.1

I'm a bit confused in this DLL-"Version"-Hell, but pulling your code locally, updating package reference in the Npgsql.Bulk.DotNetStandard21 csproj from 3.0.0 to 3.0.1 (and thus also the 4.1.0 to 4.1.1 dependency) and rebuilding gave me a working version of the library, bulk operations are going through again.

Sorry if this is not really helpful in understanding the problem, but let me know if I can assist further.

**Comment by neisbut** [comment]
Hi @Krashlog, thanks a lot for the details, that helps a lot actually! I also had same problems in another project. Now I changed references in Npgsql.Bulk for EF Core version and uploaded to NuGet. Please try the latest version when possible.

**Comment by Krashlog** [comment]
Hello @neisbut , I just updated to the 0.7.6.1 version and all my tests are now working. Glad I could be of some help tracking down the issue. Thanks again for your work, really appreciated.
