### ISSUE TITLE
Inheriting base classes is not supported

### ISSUE THREAD

**Issue by saber-wang** [neisbut/Npgsql.Bulk#36]
```
public class a
{
public  string a { get; set; }
}
public class b:a
{
}

Bulk.Insert(List<b>);
```

error:Property a not found

**Comment by neisbut** [comment]
Hi @saber-wang, sorry, but provided details are not enough to start investigations. What version of lib are you using? What framework? What model mapping? Personally I use inheritance in EF 6 version and it works fine. You can find this in SampleRunner program in this repo.

**Comment by saber-wang** [comment]
Sorry, I found that the error came from InsertAsync<T>(IEnumerable<T> entities, InsertConflictAction onConflict)

```
 await uploader.InsertAsync(xtyhbs, InsertConflictAction.UpdateProperty<XTYHB>(
                x => x.YHM,
                x => x.BMID))
```
error：Can't find property System.String YHM in mapping。

NET CORE 3.0.0+EF CORE 3.0

**Comment by neisbut** [comment]
Hi @saber-wang, sorry for such a late answer. Seems I need more information about mapping. I tried the case similar to yours here https://github.com/neisbut/Npgsql.Bulk/blob/master/src/Npgsql.Bulk.SampleRunner.DotNetStandard20/Program.cs#L179 and it worked for me.

**Comment by saber-wang** [comment]
@neisbut Hi,I wrote a test today and it's still false
sql:
```
CREATE TABLE public.test
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT test_pkey PRIMARY KEY (id)
)
```
model:
```
   [Table("test")]
    public class Test: TestBset
    {
        [Column("name")]
        public string Name { get;set; }
    }
    public class TestBset
    {
        [Column("id"),Key]
        public string Id { get; set; }
    }
```
```
List<Test> tests = new List<Test>()
            {
            new Test{ Id="1",Name="t1"},
            new Test{ Id="2",Name="t2"},
            };
            var uploader = new NpgsqlBulkUploader(_publicContext);

            await uploader.InsertAsync(tests, InsertConflictAction.UpdateProperty<Test>(
                            x => x.Id,
                            x => x.Name));
```
error:```
System.InvalidOperationException: Can't find property System.String Id in mapping
   at Npgsql.Bulk.InsertConflictAction.GetSql(EntityInfo mapping)
   at Npgsql.Bulk.NpgsqlBulkUploader.InsertAsync[T](IEnumerable`1 entities, InsertConflictAction onConflict)
```

**Comment by neisbut** [comment]
Hi @saber-wang, thanks for the details! Now I see the issue. It is a kind of mystery for me why it worked in other cases. Anyways I fixed this in the latest release. Please check when possible.

**Comment by saber-wang** [comment]
@neisbut Thank you. It's working

**Comment by zfmy** [comment]
@neisbut hi,it's not work for update
.net core 3.1 + Npgsql.Bulk 0.9


    public class EntityBase
    {
        // ignore other codes  
        public Guid Id { get; set; }  
        public DateTime? LastModificationTime { get; set; }  
    }  
    public class TestEntity : EntityBase  
    {  
        public string Name { get; set; }  
    }  

 just update LastModificationTime
`   uploader.Update(list, a => a.LastModificationTime);`

exception  
`
System.Collections.Generic.KeyNotFoundException: The given key System.Nullable1[System.DateTime] LastModificationTime' was not present in the dictionary.
`
