### ISSUE TITLE
NuGet 0.7.6.1 - Missing netstandard2.1 library

### ISSUE THREAD

**Issue by weweilep** [neisbut/Npgsql.Bulk#37]
0.7.6.1 lists netstandard2.0/2.1 with listed dependencies, but only the 2.0 library is included in the package.

Edit: this is regarding the NpgsqlBulk.EFCore package.

**Comment by neisbut** [comment]
Hi @weweilep, omg, sorry for this. Please try version 0.7.6.2.

**Comment by weweilep** [comment]
No problem, thanks for the quick fix!  Just tried it and it works as expected.  Thanks again!
