### ISSUE TITLE
bulk insert into incorrect schema

### ISSUE THREAD

**Issue by Nemet360** [neisbut/Npgsql.Bulk#43]
1. start 2 instances of the same types but with DIFFERENT schemas
2. bulk insert the 2 instances the same type of entity

BUG: 
all the items are being inserted into 1 schema since the cache concurrent dictionary in NpgsqlBulkUploader.cs is blocking on type and not considering that the same type may exists on several schema (but on the same database)

**Comment by rdunn-geoplan** [comment]
There's a simple fix for this, @neisbut could you please incorporate the code below in the NpgsqlBulkUploader constructor?  It seems this repo doesn't allow pull requests?

```c#
    public NpgsqlBulkUploader(DbContext context, bool clearCache = false)
    {
        this.context = context;

	if (clearCache)
	{
            Cache.Clear();
	}
    }
```

**Comment by neisbut** [comment]
Hi guys, sorry for a late answer (I was off for a long time).. Please help me to understand this issue better. You use same entity type in a different context (mean different context type) OR you use same entity type, same context type, but (only) for another schema ?

**Comment by neisbut** [comment]
Hi again, support for same entity type in different contexts is implemented, please check if it fits your needs.
