### ISSUE TITLE
Npgsql.Bulk doesn't work with adding bulk entities with relations

### ISSUE THREAD

**Issue by MAlshehri** [neisbut/Npgsql.Bulk#58]
Hi, 
I tried to add a bulk of entities with many-to-many relationships but it failed and I got this message "23502: null value in column "Id" of relation "Entity" violates not-null constraint"

why it doesn't auto-increments ?

**Comment by neisbut** [comment]
Hi @MAlshehri , sorry, this is not supported. And no plans to implement this.
