### ISSUE TITLE
Npgsql.PostgresException (0x80004005): 42P01: relation "_temp__a9f93f82_03f3_4137_8020_ecedb8cc7612_46" does not exist

### ISSUE THREAD

**Issue by GeorgyRezchikov** [neisbut/Npgsql.Bulk#64]
With a heavy load and a limited number of simultaneously available connections (40 connections to the database), I get the following error: 
Npgsql.PostgresException (0x80004005): 42P01: relation "_temp__a9f93f82_03f3_4137_8020_ecedb8cc7612_46" does not exist.
I use the following connection string "Host = ***; Port = ***; Database = ***; Username = ***; ***; Pooling = false; Minimum Pool Size = 0; Maximum Pool Size = 100; CommandTimeout = 600; No Reset On Close = true; "
Pooling = false is used on purpose, the connection to the database goes through pgbouncer.
As I understand it, after creating the temporary table, another connection is used to insert data, can this situation be avoided?

**Comment by neisbut** [comment]
Hi @GeorgyRezchikov , this should be fixed now.
