### ISSUE TITLE
Incorrect behaviour where the same table is present in defferent schemas

### ISSUE THREAD

**Issue by mwolszleger** [neisbut/Npgsql.Bulk#67]
I have two same tables (so one class in C#) in different schemas. And having two instances of NpgsqlBulkUploader (for differents schemas), both of them insert values to one table. 
The problem will be solved, if this static dictionary's key in NpgsqlBulkUploader contains also schema name.
```
  private EntityInfo GetEntityInfo<T>()
        {
            var key = $"{context.GetType().FullName}-{typeof(T).FullName}";
            if (Cache.TryGetValue(key, out EntityInfo info))
            {
                return info;
            }
```

**Comment by neisbut** [comment]
Hi @mwolszleger , thanks for suggestion, this should be fixed in recent 0.10 release.
