### ISSUE TITLE
Awesome project, but Entity Framework :(

### ISSUE THREAD

**Issue by flo8** [neisbut/Npgsql.Bulk#8]
The idea of this project is great and much needed! Is it possible to use it without Entity Framework and rely on Npgsql only? The error messages from EF are extremely hard to debug at times, I got the "Sequence contains not matching elements" for some reason and very hard to find root cause by the exception.
Again, thanks for the great work!

**Comment by neisbut** [comment]
Hi @flo8, sorry for a late response. Theretically that's possible, but sorry for now I don't have enough time to do it. Sorry again. But the good news is that some time ago I faced issue with exactly same exception message and fixed it. Maybe you could try latest version and it will work better for you?
